version: '3'

services:
  web:
    image: nginx:latest
    ports:
     - 80:80
     - 443:443
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ../dist/:/var/www/data/:ro